### ISSUE TITLE
Errors on test run 

### ISSUE THREAD

**Issue by ntbm** [dnkrsl/time#2]
`Module not found: Error: Can't resolve 'components/kanbanBoard/Lane.js'`

`Module not found: Error: Can't resolve 'components/kanbanBoard/Note.js'`

`Module not found: Error: Can't resolve 'components/kanbanBoard/Notes.js'`

`Module not found: Error: Can't resolve 'react-test-renderer/shallow'`

`PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: 'Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.'
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: 'Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.'
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "components/YeomanImage"
  at webpack:///test/components/YeomanImageTest.js:3:0 <- test/loadtests.js:52871
`

**Comment by dnkrsl** [comment]
Deleted Tests for now 


first i need to work that out
https://stackoverflow.com/questions/41148602/how-should-i-unit-test-mapdispatchtoprops-in-redux
